### PR TITLE
Added submenu

### PR DESCRIPTION
**Pull request by angelskieglazki**
I added submenu for Linux. Sorry. Later I'll try to add icons

### CODE REVIEW

**Comment by zserge** [comment]
That's a good start, thanks! I would try to make it in a recursive manner, though (now submenus are limited to one level only and have no checked state support etc). Also probably it would be possible to reuse the same callback for "activate" signal.

**Comment by angelskieglazki** [comment]
@zserge   "a recursive manner"  I thought as much:)  I'll do a recursive. Thanks for reply.

**Comment by angelskieglazki** [comment]
Hello. I redid all.

**Comment by zserge** [comment]
That's much better, well done! May I ask you to use `clang-format` tool to re-format the code to be consistent (default settings should work fine, the original code was formatted like that). Also I'd recommend to remove the commented-out block in example.c (lines 48..65) as it doesn't bring any sense to the example. Then I'd be happy to merge it.

**Comment by angelskieglazki** [comment]
Update.   I hope I did the right.

**Comment by zserge** [comment]
I've simplified it a little bit and added implementations for winapi and macos. Congratulations, sub-menus are now done!

**Pull request merged**
